# Generated by Django 4.0.1 on 2022-01-21 18:52

from django.db import migrations, models
import main.utils.unique_id


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_uuid_image_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='source',
            new_name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='unique_id',
            field=models.CharField(default=main.utils.unique_id.generate_unique_id, max_length=50),
        ),
    ]
